[project]
name = "lolaramhelper"
version = "1.2"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx",
    "loguru",
    "psutil",
    "requests",
    "websockets",
]

[dependency-groups]
dev = [
    "pyinstaller>=6.13.0",
]
